services:

  db:
    image: postgres:16.2
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cache:
    image: redis:7.2.4
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    # look for Dockerfile
    build: .

    # ? this is development server command
#    command:  ["./wait-for-it.sh", "db:5432", "--",
#                "python", "/code/educa/manage.py", "runserver",
#                "0.0.0.0:8000"]

    command: ["./wait-for-it.sh", "db:5432", "--",
              "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    restart: always
    # persistent data used by Docker container
    volumes:
      - .:/code
    # ? settings for development server
#    ports:
#      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # order of services to run
    depends_on:
      - db
      - cache

  nginx:
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./config/nginx:/etc/nginx/templates
      - .:/code
    ports:
      # http and https
      - "80:80"
      - "443:443"

  daphne:
    build: .
    working_dir: /code/educa/
    command: [ "../wait-for-it.sh", "db:5432","--",
               "daphne", "-b", "0.0.0.0", "-p", "9001",
               "educa.asgi:application" ]
    restart: always
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - cache
